# Use the new docker based infrastructure
sudo: false

language: node_js
node_js:
- 0.10.40

git:
  submodules: false

# On travis's new docker based sudoless infastructure, meteor can't be linked to /usr/local/bin,
# so we have to add meteor to the PATH
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
- curl https://install.meteor.com | /bin/sh
- export PATH="$HOME/.meteor:$PATH"
- meteor --version
